# Site settings
title: Wired Radio
email: yo@wiredradio.co.uk
description: "official description goes here"
baseurl: ""
url: "http://wiredradio.github.io"
twitter_username: wiredgold
github_username:  wiredradio

# Build settings
markdown: kramdown
permalink: pretty
